Gracefully handle "sentry-trace" headers that don't match the regexp
getsentry/sentry-ruby pull request #1265
Opened 2021-02-04 03:48 UTC by lfittl

Fixes the handling of invalid "sentry-trace" header values, such as "null", that otherwise lead to an application crash.

Related error backtrace:

```
Rack app error handling request { POST /graphql }
#<NoMethodError: undefined method `[]' for nil:NilClass>
.../sentry-ruby-core-4.1.6/lib/sentry/transaction.rb:32:in `from_sentry_trace'
.../sentry-ruby-core-4.1.6/lib/sentry/rack/capture_exceptions.rb:21:in `block in call'
.../sentry-ruby-core-4.1.6/lib/sentry/hub.rb:52:in `with_scope'
.../sentry-ruby-core-4.1.6/lib/sentry-ruby.rb:149:in `with_scope'
.../sentry-ruby-core-4.1.6/lib/sentry/rack/capture_exceptions.rb:14:in `call'
```

2021-02-04 04:10 UTC, st0012 approved these changes
thanks for the fix! can you add a new changelog entry for this as well? thx

2021-02-04 04:35 UTC, st0012 requested changes
actually, can you add a test case to `capture_exceptions_spec.rb`?

2021-02-04 06:06 UTC, lfittl commented
@st0012 Done - I've also found an adjacent bug, added in a follow-up commit in this PR, since its in the same code area (happy to move to a separate PR if you prefer).

2021-02-04 07:23 UTC, st0012 commented
@lfittl thanks for the update 👍 some thoughts:

1. I still want to see a test in `spec/sentry/rack/capture_exceptions_spec.rb` for the invalid sentry case. I suspect that this change breaks the middleware because it assumes `span` won't be `nil` in any case.
2. the issue you mentioned is indeed a problem, but I'm not sure if adding the sampling decision is the right answer. I think the correct solution is to change `sentry-rails`'s condition on instrumentation. I'll open a PR for that.

2021-02-04 08:36 UTC, lfittl commented
> 1. I still want to see a test in `spec/sentry/rack/capture_exceptions_spec.rb` for the invalid sentry case. I suspect that this change breaks the middleware because it assumes `span` won't be `nil` in any case.

Good catch - fixed now. I assume we'd want to run through the regular logic in this case.

> 2. the issue you mentioned is indeed a problem, but I'm not sure if adding the sampling decision is the right answer. I think the correct solution is to change `sentry-rails`'s condition on instrumentation. I'll open a PR for that.

Ack, removed again from this PR. Thanks!

2021-02-04 12:36 UTC, st0012 reviewed
thanks for catching the issue and proposed the great fix 😄 

because I just released `4.2.0` earlier today, can you rebase the branch and update the changelog again?

```
# Changelog

## Unreleased <- Add this

< and put the entry here >

## 4.2.0
.....
```

2021-02-04 22:39 UTC, lfittl commented
@st0012 Done - rebased & updated change log entry.

2021-02-05 01:42 UTC, st0012 approved these changes

2021-02-05 01:42 UTC, merged

2021-02-05 09:17 UTC, st0012 commented
@lfittl I've talked to other maintainers about the other issue you spotted in this PR. and the answer is that the child transactions initialized from `.from_sentry_trace` should just inherit the parent's sampling decision. I've added https://github.com/getsentry/sentry-ruby/pull/1269 to update this.