always convert trusted proxies to string
getsentry/sentry-ruby pull request #1288
Opened 2021-02-15 15:11 UTC by gagalago

fix https://github.com/getsentry/sentry-ruby/issues/1274

## Description
`IPAddr.new` only accept the address as a string but not as an `IPAddr` as suggested in the [Rails documentation](https://api.rubyonrails.org/classes/ActionDispatch/RemoteIp.html).

2021-02-15 15:13 UTC, woidda approved these changes

2021-02-15 15:14 UTC, mihaic195 approved these changes

2021-02-15 15:27 UTC, st0012 requested changes
thanks for the PR, but I think the solution can still be improved 🙂 

although `sentry-rails` is where most users would register the trusted proxies, `config.trusted_proxies` is also a public configuration option. so even though the PR can stop most of the problematic cases, it doesn't prevent users from manually injecting the converted ip addresses. imo, it's the `Utils::RealIP`'s responsibility to check every ip address' type and whether to convert them.

also, there should be test cases to cover the situation this PR wants to address.

2021-02-16 08:59 UTC, woidda approved these changes

2021-02-16 15:50 UTC, st0012 approved these changes
thanks for the fix! can you also add a changelog entry?

2021-02-16 17:15 UTC, gagalago commented
> thanks for the fix! can you also add a changelog entry?

I did it by hand. As it's not possible to do it with craft when it's not the master branch. 

Can be interesting for next time :wink:  to add on the `CONTRIBUTING.md` or in the pull request template who is responsible to add the entry in the changelog and how to do it in a feature branch (to be compatible later with craft).

2021-02-16 17:21 UTC, st0012 commented
@gagalago thanks for the advice 😄 I also add changelogs by hand tbh. but I'll mention the changelog entry in the pr template 👍

2021-02-16 17:21 UTC, merged