Allow customization breadcrumb data of ActiveSupportLogger
getsentry/sentry-ruby pull request #2139
Opened 2023-10-13 17:48 UTC by igordepolli

Ref: #2135 

## Description
The idea is to allow the initialization configuration to manipulate the attributes that will be shown in the ActiveSupportLogger breadcrumbs.

2023-10-23 12:52 UTC, sl0thentr0py requested changes
thx @igordepolli!
one small change then good to go

2023-10-23 12:52 UTC, sl0thentr0py commented on sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
> +            allowed_keys = Sentry.configuration.rails.active_support_logger_subscription_items[name]
can you pass in the configuration list from `inject` like this? there are some multi-threaded edge cases with accessing `Sentry.configuration` that this avoids.

```patch
➜  sentry-rails git:(igordepolli/master) ✗ git --no-pager diff
diff --git a/sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb b/sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
index 3af825d2..9dfdd1d2 100644
--- a/sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
+++ b/sentry-rails/lib/sentry/rails/breadcrumb/active_support_logger.rb
@@ -7,10 +7,8 @@ module Sentry
             # skip Rails' internal events
             return if name.start_with?("!")

-            allowed_keys = Sentry.configuration.rails.active_support_logger_subscription_items[name]
-
             if data.is_a?(Hash)
-              data = data.slice(*allowed_keys)
+              data = data.slice(*@allowed_keys[name])
             end

             crumb = Sentry::Breadcrumb.new(
@@ -21,7 +19,9 @@ module Sentry
             Sentry.add_breadcrumb(crumb)
           end

-          def inject
+          def inject(allowed_keys)
+            @allowed_keys = allowed_keys
+
             @subscriber = ::ActiveSupport::Notifications.subscribe(/.*/) do |name, started, finished, unique_id, data|
               # we only record events that has a started timestamp
               if started.is_a?(Time)
diff --git a/sentry-rails/lib/sentry/rails/railtie.rb b/sentry-rails/lib/sentry/rails/railtie.rb
index 4e04d0e3..f77a2b7e 100644
--- a/sentry-rails/lib/sentry/rails/railtie.rb
+++ b/sentry-rails/lib/sentry/rails/railtie.rb
@@ -89,7 +89,7 @@ module Sentry
     def inject_breadcrumbs_logger
       if Sentry.configuration.breadcrumbs_logger.include?(:active_support_logger)
         require 'sentry/rails/breadcrumb/active_support_logger'
-        Sentry::Rails::Breadcrumb::ActiveSupportLogger.inject
+        Sentry::Rails::Breadcrumb::ActiveSupportLogger.inject(Sentry.configuration.rails.active_support_logger_subscription_items)
       end

       if Sentry.configuration.breadcrumbs_logger.include?(:monotonic_active_support_logger)
```

2023-10-23 12:54 UTC, sl0thentr0py commented on CHANGELOG.md
> +- Add new `config.rails.active_support_logger_subscription_items` to allow customization breadcrumb data of active support logger
```suggestion
- Add new `config.rails.active_support_logger_subscription_items` to allow customization breadcrumb data of active support logger [#2139](https://github.com/getsentry/sentry-ruby/pull/2139)
```

2023-10-23 22:15 UTC, igordepolli commented
> thx @igordepolli! one small change then good to go

@sl0thentr0py Done. Ty for review :)

2023-10-23 22:53 UTC, st0012 commented on sentry-rails/lib/sentry/rails/configuration.rb
> +      attr_accessor :active_support_logger_subscription_items
Could you add some docs for it?

2023-10-23 22:53 UTC, st0012 commented on sentry-rails/spec/sentry/rails/breadcrumbs/active_support_logger_spec.rb
> +      Sentry.configuration.rails.active_support_logger_subscription_items["process_action.action_controller"] << :controller
You need to add this in a `ensure` block so it doesn't affect other tests if the test failed.

2023-10-23 23:27 UTC, igordepolli commented
@st0012 Done. Good catch! Ty! :)

2023-10-24 12:08 UTC, sl0thentr0py approved these changes

2023-10-24 12:17 UTC, sl0thentr0py commented
@igordepolli the `ensure` fails on ruby 2.4 because this feature was added in 2.5, you can either add a `begin/end` or just wrap the spec in a `context` with a `before/after` which is probably cleaner.

https://github.com/getsentry/sentry-ruby/actions/runs/6620176438/job/17999733560?pr=2139#step:5:156

You can also just give me [push rights to the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I'll take care of the rest and merge this in.

2023-10-24 12:25 UTC, igordepolli commented
> @igordepolli the `ensure` fails on ruby 2.4 because this feature was added in 2.5, you can either add a `begin/end` or just wrap the spec in a `context` with a `before/after` which is probably cleaner.
> 
> https://github.com/getsentry/sentry-ruby/actions/runs/6620176438/job/17999733560?pr=2139#step:5:156
> 
> You can also just give me [push rights to the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I'll take care of the rest and merge this in.

@sl0thentr0py Oh, sorry for the inconvenience. You already have the right to manipulate PR however you want, feel free.

2023-10-24 12:34 UTC, merged