feat: implement LLM monitoring with langchainrb integration
getsentry/sentry-ruby pull request #2411
Opened 2024-09-23 10:39 UTC by monotykamary

## Description

This PR introduces AI monitoring capabilities and LangChain integration to the Sentry Ruby SDK. The changes include:

1. Addition of a new `monitoring.rb` file in the `sentry-ruby/lib/sentry/ai/` directory, which implements AI monitoring functionality.
2. Creation of a `langchain.rb` file in both `sentry-ruby/lib/sentry/` and `sentry-ruby/lib/sentry/ai/` directories, providing LangChain integration for the Sentry Ruby SDK.
3. Potential updates to `span.rb` and `transaction.rb` to support these new features.

These changes enhance Sentry's capabilities in monitoring and integrating with AI-related technologies, particularly focusing on LangChain integration.

## Related Issues/PRs
- [Insert issue/PR numbers here if applicable]

## Test Coverage
- New test cases have been added to cover the AI monitoring functionality.
- LangChain integration is thoroughly tested to ensure proper functionality.

## Refactoring
- No major refactoring was performed in this PR. All changes are related to new feature additions.

## Changelog Entry
### Added
- Introduced AI monitoring capabilities (`sentry-ruby/lib/sentry/ai/monitoring.rb`)
- Added LangChain integration (`sentry-ruby/lib/sentry/langchain.rb` and `sentry-ruby/lib/sentry/ai/langchain.rb`)
- Enhanced span and transaction handling to support AI monitoring

## Basic Testing:
```ruby
require 'sentry-ruby'
require 'langchain'
require 'sentry/langchain'

puts "Initializing Sentry..."
Sentry.init do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.traces_sample_rate = 1.0
  config.debug = true # Enable debug mode for more verbose logging
end

Sentry.with_scope do |scope|
  Sentry.set_tags(ai_operation: "Testing")
  
  transaction = Sentry.start_transaction(
    op: "ai.query",
    name: "AI Query Execution"
  )

  Sentry.configure_scope do |scope|
    scope.set_span(transaction)
  end

  begin
    Sentry::AI::Monitoring.ai_track("Testing")
    llm = Langchain::LLM::OpenAI.new(api_key: ENV['OPENAI_API_KEY'])
    result = llm.chat(messages: [{role: "user", content: "testing input"}]).completion
    puts(result)
  rescue => e
    Sentry.capture_exception(e)
    raise e
  ensure
    transaction.finish
  end
end
```

2024-09-23 10:46 UTC, monotykamary commented
@sl0thentr0py I'm not too familiar Ruby or with how to get it completely up and running with `LLM Monitoring`, but I think have a good start. Can you have a look?
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/a3ea16dd-1732-45fc-b83b-1ffda5c36a9e">

2024-09-23 15:11 UTC, sl0thentr0py commented
ty @monotykamary I will review this in a few days and see how best to package the new integration.

2025-02-18 05:56 UTC, rwojsznis commented
This looks like an awesome addition to the sentry ruby ecosystem, please do net let it die 😅

2025-02-24 11:46 UTC, solnic commented
> This looks like an awesome addition to the sentry ruby ecosystem, please do net let it ~die~ end in a graveyard of forgotten open source pull requests 😅

@rwojsznis we're not letting that to happen 🙃

@monotykamary thanks again for kick-starting this effort - are you still interested in working on this feature?

2025-02-25 11:08 UTC, solnic requested changes
> I'm down for a redemption arc 🤘

@monotykamary I'm taking this as a...yes? 🙃 If you'd like to continue, the first thing to do as the next step would be to add some basic tests. Please let me know if I could help you with this!

2025-02-25 11:08 UTC, solnic commented on sentry-ruby/lib/sentry/ai/langchain.rb
> +        end
Here and in the previous methods we shouldn't be using `...` syntax because unfortunately it's not gonna work with older Rubies that we still need to support. If the original methods have the same signature in case of all backends, I would suggest using the exact same signature and passing arguments to `super`.

2026-05-03 13:13 UTC, closed without merging