RescuedExceptionInterceptor: Handle empty configuration
getsentry/sentry-ruby pull request #2428
Opened 2024-10-10 21:43 UTC by MrSerth

Previously, it could happen that `Sentry.configuration` was `nil`. In this case, calling `rails` would produce a `NoMethodError`. We fix this issue by using safe navigation.

Furthermore, this commit ensures we use a reasonable default in case the configuration couldn't be loaded. Since the config `report_rescued_exceptions` defaults to `true`, we assume this value here, too.
 
Fixes #2386

2024-10-17 11:18 UTC, solnic requested changes

2024-10-19 12:19 UTC, MrSerth commented on sentry-rails/lib/sentry/rails/rescued_exception_interceptor.rb
> +        report_rescued_exceptions = Sentry.configuration&.rails&.report_rescued_exceptions
I added a comment and linked to the issue.

2024-10-28 07:46 UTC, solnic commented
Sorry but I'm having second thoughts about this, it's the same as I outlined here https://github.com/getsentry/sentry-ruby/pull/2396#issuecomment-2440715857

2024-10-28 16:26 UTC, solnic approved these changes

2024-10-28 16:42 UTC, MrSerth commented
I've had a quick look at the two test failures. The [second one](https://github.com/getsentry/sentry-ruby/actions/runs/11506103055/job/32170476742?pr=2428) is caused by Docker Pull Limits, the first one failed when setting up Ruby 2.5. Both don't look related, I'd say. How can we proceed here?

2024-10-28 18:21 UTC, solnic commented
> I've had a quick look at the two test failures. The [second one](https://github.com/getsentry/sentry-ruby/actions/runs/11506103055/job/32170476742?pr=2428) is caused by Docker Pull Limits, the first one failed when setting up Ruby 2.5. Both don't look related, I'd say. How can we proceed here?

I handled those failures. We should be good to merge this.

2024-10-28 18:21 UTC, merged