Make Sentry.{close,get_main_hub} thread-safe
getsentry/sentry-ruby pull request #2436
Opened 2024-10-18 08:23 UTC by solnic

Since we're dealing with a bunch of global vars in `Sentry.close`, it should be wrapped in a mutex sync because threads may be accessing these vars while Sentry is closing, and THAT *probably* causes #2386 and #2396.

#skip-changelog

2024-10-18 10:25 UTC, solnic commented
`Sentry.initialized?` should use a mutex too, given that it relies on `@main_hub` that may get reset to `nil` by `Sentry.close`

2024-10-18 12:14 UTC, sl0thentr0py requested changes

2024-10-18 12:14 UTC, sl0thentr0py commented on sentry-ruby/lib/sentry-ruby.rb
> +        @main_hub = nil
let's just wrap lines 282 and 283 in the mutex, the other stuff is fine.
And I agree that `get_main_hub` should also be within a mutex sync

2024-10-18 21:44 UTC, sl0thentr0py approved these changes

2024-10-19 21:00 UTC, st0012 approved these changes

2024-10-20 21:45 UTC, merged