Default to internal_error rather than unknown_error
getsentry/sentry-ruby pull request #2473
Opened 2024-11-23 01:32 UTC by cyberdelia

When using `sentry-opentelemetry` to trace code that isn't related to an HTTP call, the `SpanProcessor` will convert set the status of a `Transaction` to be `"unknown_error"`, which is benign, but within Sentry UI this status is not interpreted as an error at all. 

The result is that all the impacted transactions appears to have 0% failure rate, etc. Changing it to `"internal_error"` prevents this, and also is in line with [other sentry SDKs](https://github.com/getsentry/sentry-python/blob/a7c2d704a90b374bc3c6a69365922614710d95f7/sentry_sdk/integrations/opentelemetry/span_processor.py#L304) behaviour.

Sidebar:  The `SpanEvent` metadata around exceptions seems to be dropped in the conversion process to `Transaction` , which is too bad.

2024-11-28 12:35 UTC, solnic requested changes
This makes sense, thanks. Could you also add a simple spec that covers this change to span_processor_spec.rb?

2024-11-28 17:27 UTC, cyberdelia commented
@solnic Done.

2024-12-05 20:03 UTC, solnic approved these changes
Looks good, thank you! Please update the top-level CHANGELOG.md too, and I'll be able to merge it in 🙂

2024-12-15 19:40 UTC, cyberdelia commented
@solnic Done!

2024-12-19 07:54 UTC, merged